
data<-read.csv("C:\\Users\\User\\Desktop\\Cheeseboard.csv", sep=",", head=TRUE)
data$GROUPS<-factor(data$GROUPS,c("2N", "Ts65Dn"))
data$DAYS<-as.factor(data$DAYS)
lineplot.CI(data$DAYS,data$LATENCY,group=data$GROUPS,type="b", x.cont=FALSE,col=c("Pink","Purple"), fixed=TRUE,lwd=3,cex.axis=1.25,ylab="Mean Latency (s)",xlab="Blocks of 4 Trials",cex.lab=1.5,cex.main=1.75,main="Dryland Version of the Morris Water Maze",pch="O",lty=c(1,6),bg="black",x.leg=3.25)
x11()
lineplot.CI(data$DAYS,data$PercentLATENCY,group=data$GROUPS,type="b", x.cont=FALSE,col=c("Pink","Purple"), fixed=TRUE,lwd=3,cex.axis=1.25,ylab="Percent Latency Compared to Block 1",xlab="Blocks of 4 Trials",cex.lab=1.5,cex.main=1.75,main="Dryland Version of the Morris Water Maze",pch="O",lty=c(1,6),bg="black",x.leg=3.25)
x11()
lineplot.CI(data$DAYS,data$DISTANCE,group=data$GROUPS,type="b", x.cont=FALSE,col=c("Pink","Purple"), fixed=TRUE,lwd=3,cex.axis=1.25,ylab="Mean Distance (cm)",xlab="Blocks of 4 Trials",cex.lab=1.5,cex.main=1.75,main="Dryland Version of the Morris Water Maze",pch="O",lty=c(1,6),bg="black",x.leg=3.25)
x11()
lineplot.CI(data$DAYS,data$PercentDISTANCE,group=data$GROUPS,type="b", x.cont=FALSE,col=c("Pink","Purple"), fixed=TRUE,lwd=3,cex.axis=1.25,ylab="Percent Distance Compared to Block 1",xlab="Blocks of 4 Trials",cex.lab=1.5,cex.main=1.75,main="Dryland Version of the Morris Water Maze",pch="O",lty=c(1,6),bg="black",x.leg=3.25)
