install.packages("gplots")
library(gplots)
#pdf("~/Desktop/Endophenotype.pdf",paper="USr")
data1$GROUP<-factor(data1$GROUP,c("WT","LOW_CGG","HIGH_CGG","2N","Ts65Dn"))
data2$GROUP<-factor(data2$GROUP,c("WT","LOW_CGG","HIGH_CGG","FXS", "2N","Ts65Dn"))
par(mfrow=c(1,5))
par(oma=c(4,4,4,4))
boxplot(METRIC~GROUP,data=data2,col=c("Red","LightGreen","Orange","Blue","Pink","Purple"),main="Coordinate",ylab="Mean Ratio Value [0,1]",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,xlim=c(0,8),at=c(1,2,3,4, 6,7),outcex=2)
boxplot(TOPOLO~GROUP,data=data2,col=c("Red","LightGreen","Orange","Blue","Pink","Purple"),main="Categorical",ylab="Mean Ratio Value [0,1]",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,xlim=c(0,8),at=c(1,2,3,4, 6,7),outcex=2)
boxplot(T_ORDER~GROUP,data=data2,col=c("Red","LightGreen","Orange","Blue","Pink","Purple"),main="Temporal Order",ylab="Mean Ratio Value [-1,1]",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,xlim=c(0,8),at=c(1,2,3,4, 6,7),outcex=2)
boxplot(NOVELTY~GROUP,data=data2,col=c("Red","LightGreen","Orange","Blue","Pink","Purple"),main="Novelty Detection",ylab="Mean Ratio Value [-1,1]",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,xlim=c(0,8),at=c(1,2,3,4, 6,7),outcex=2)
boxplot(RUNGWALK~GROUP,data=data1,col=c("Red","LightGreen","Orange","Pink","Purple"),main="Parallel Beam Walk",ylab="Number of Foot Slips in 60s (Adjusted)",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,xlim=c(0,8),at=c(1,2,3, 6,7),outcex=2)
mtext("NEUROBEHAVIORAL ENDOPHENOTYPE: FRAGILE X DISORDERS AND DOWN SYNDROME MOUSE MODELS",side=3,outer=T,cex=1.5,line=2)
#dev.off()

quartz()
install.packages("gplots")
library(gplots)
data$GROUP<-factor(data$GROUP,c("WT","LOW_CGG","HIGH_CGG","FXS"))
par(mfrow=c(1,4))
par(oma=c(4,4,4,4))
boxplot(METRIC~GROUP,data=data,col=c("Red","LightGreen","Orange","Blue"),main="Coordinate",ylab="Mean Ratio Value [0,1]",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,outcex=2)
boxplot(TOPOLO~GROUP,data=data,col=c("Red","LightGreen","Orange","Blue"),main="Categorical",ylab="Mean Ratio Value [0,1]",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,outcex=2)
boxplot(T_ORDER~GROUP,data=data,col=c("Red","LightGreen","Orange","Blue"),main="Temporal Order",ylab="Mean Ratio Value [-1,1]",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,outcex=2)
boxplot(NOVELTY~GROUP,data=data,col=c("Red","LightGreen","Orange","Blue"),main="Novelty Detection",ylab="Mean Ratio Value [-1,1]",las=2,cex.axis=1.25,cex.lab=1.25,lwd=2,outcex=2)
mtext("NEUROBEHAVIORAL ENDOPHENOTYPE: FRAGILE X DISORDERS",side=3,outer=T,cex=1.5,line=2)

