####Spatiotemporal Context#####
spatiotemporal<-read.csv("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Data/DSBATTERY.csv",head=TRUE, sep=",")
Metric_Red<-aov(spatiotemporal$METRIC_RED~spatiotemporal$GROUPS)
Metric_Clear<-aov(spatiotemporal$METRIC_CLEAR~spatiotemporal$GROUPS)
Topological_Red<-aov(spatiotemporal$TOPOLOGICAL_RED~spatiotemporal$GROUPS)
Topological_Clear<-aov(spatiotemporal$TOPOLOGICAL_CLEAR~spatiotemporal$GROUPS)
LocationRecognition_Red<-aov(spatiotemporal$LOCREC_RED~spatiotemporal$GROUPS)
LocationRecognition_Clear<-aov(spatiotemporal$LOCREC_CLEAR~spatiotemporal$GROUPS)
ObjectRecognition_1hr_Red<-aov(spatiotemporal$OBJECTREC_RED~spatiotemporal$GROUPS)
ObjectRecognition_1hr_Clear<-aov(spatiotemporal$OBJECTREC_CLEAR~spatiotemporal$GROUPS)
ObjectRecognition_24hr_Red<-aov(spatiotemporal$OBJECTREC_24_RED~spatiotemporal$GROUPS)
ObjectRecognition_24hr_Clear<-aov(spatiotemporal$OBJECTREC_24_CLEAR~spatiotemporal$GROUPS)
Ambiguity_Red<-aov(spatiotemporal$AMBIGUOUS_RED~spatiotemporal$GROUPS)
Ambiguity_Clear<-aov(spatiotemporal$AMBIGUOUS_CLEAR~spatiotemporal$GROUPS)
Ambiguity_Control_Red<-aov(spatiotemporal$AMBIGUOUS_CTRL_RED~spatiotemporal$GROUPS)
Ambiguity_Control_Clear<-aov(spatiotemporal$AMBIGUOUS_CTRL_CLEAR~spatiotemporal$GROUPS)
NoveltyDetection_Red<-aov(spatiotemporal$NOVEL_RED~spatiotemporal$GROUPS)
NoveltyDetection_Clear<-aov(spatiotemporal$NOVEL_CLEAR~spatiotemporal$GROUPS)
TemporalOrder_Red<-aov(spatiotemporal$TEMPORAL_RED~spatiotemporal$GROUPS)
TemporalOrder_Clear<-aov(spatiotemporal$TEMPORAL_CLEAR~spatiotemporal$GROUPS)
DelayedAlternation<-aov(spatiotemporal$ALTERNATIONS~spatiotemporal$GROUPS)
#####Cheeseboard###
cheeseboard<-read.csv("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Data/Cheeseboard.csv",head=TRUE, sep=",")
Cheeseboard_RawLatency<-aov(cheeseboard$LATENCY~cheeseboard$GROUPS*cheeseboard$DAYS+Error(1/cheeseboard$DAYS))
Cheeseboard_ScaledLatency<-aov(cheeseboard$PercentLATENCY~cheeseboard$GROUPS*cheeseboard$DAYS+Error(1/cheeseboard$DAYS))
Cheeseboard_RawDistance<-aov(cheeseboard$DISTANCE~cheeseboard$GROUPS*cheeseboard$DAYS+Error(1/cheeseboard$DAYS))
Cheeseboard_ScaledDistance<-aov(cheeseboard$PercentDISTANCE~cheeseboard$GROUPS*cheeseboard$DAYS+Error(1/cheeseboard$DAYS))
####Capellini#####
capellini<-read.csv("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Data/Capellini.csv",head=TRUE, sep=",")
Capellini_Latency<-aov(capellini$Latency~capellini$GROUP)
Capellini_PawsTogether<-aov(capellini$Atypical_Paw_Together~capellini$GROUP)
Capellini_NoContact<-aov(capellini$Atypical_NoContact~capellini$GROUP)
Capellini_MouthPull<-aov(capellini$Atypical_Mouth_Pull~capellini$GROUP)
Capellini_OverallAtypical<-aov(capellini$Sum_Atypical~capellini$GROUP)
###Nesting########
nesting<-read.csv("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Data/Nesting.csv",head=TRUE, sep=",")
Nesting_Contact<-aov(nesting$latency_contact~nesting$group)
Nesting_Dig<-aov(nesting$latency_dig~nesting$group)
Nesting_Complete<-aov(nesting$latency_finish~nesting$group)
###Anxiety########
neophagia<-read.csv("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Data/Hyponeophagia.csv",head=TRUE, sep=",")
Neophagia_NovelFood<-aov(neophagia$latency_novelfood~neophagia$group)
Neophagia_NovelEnvironment<-aov(neophagia$latency_novelenvironment~neophagia$group)
Neophagia_NovelBoth<-aov(neophagia$latency_both~neophagia$group)
##Ladder Rung Walking###
ladder<-read.csv("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Data/DSLADDER.csv",head=TRUE, sep=",")
Ladder_Raw<-aov(ladder$Ladder_RAW~ladder$groups)
Ladder_Adjusted<-aov(ladder$Ladder_ADJUSTED~ladder$groups)
####Response_Learning#####
response_learning<-read.csv("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Data/Response_learning.csv",head=TRUE, sep=",")
Response_Learning<-aov(response_learning$Percent_Correct~response_learning$GROUP*response_learning$DAY+Error(1/response_learning$DAY))
#####Reversal Factors##########
response_factors<-read.csv("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Data/Reversal_Factors.csv",head=TRUE, sep=",")
Reversal_Changepoint<-aov(response_factors$response_changepoints~response_factors$group)
Reversal_Perseverative<-aov(response_factors$response_perseverative~response_factors$group)
Reversal_Regressive<-aov(response_factors$response_regressive~response_factors$group)
#############
sink("/Users/marlys/Ryan_GITHUB_REPOSITORIES/Ts65DnPilots/Ts65DnStatistics.txt")
print(" ")
print("Metric_Red")
print(summary(Metric_Red))
print(" ")
print("Metric_Clear")
print(summary(Metric_Clear))
print(" ")
print("Topological_Red")
print(summary(Topological_Red))
print(" ")
print("Topological_Clear")
print(summary(Topological_Clear))
print(" ")
print("LocationRecognition_Red")
print(summary(LocationRecognition_Red))
print(" ")
print("LocationRecognition_Clear")
print(summary(LocationRecognition_Clear))
print(" ")
print("ObjectRecognition_1hr_Red")
print(summary(ObjectRecognition_1hr_Red))
print(" ")
print("ObjectRecognition_24hr_Red")
print(summary(ObjectRecognition_24hr_Red))
print(" ")
print("ObjectRecognition_1_hr_Clear")
print(summary(ObjectRecognition_1hr_Clear))
print(" ")
print("ObjectRecognition_24_hr_Clear")
print(summary(ObjectRecognition_24hr_Clear))
print(" ")
print("Ambiguity_Red_Red")
print(summary(Ambiguity_Red))
print(" ")
print("Ambiguity_Clear")
print(summary(Ambiguity_Clear))
print(" ")
print("Ambiguity_Control_Red")
print(summary(Ambiguity_Control_Red))
print(" ")
print("Ambiguity_Control_Clear")
print(summary(Ambiguity_Control_Clear))
print(" ")
print("NoveltyDetection_Red")
print(summary(NoveltyDetection_Red))
print(" ")
print("NoveltyDetection_Clear")
print(summary(NoveltyDetection_Clear))
print(" ")
print("TemporalOrder_Red")
print(summary(TemporalOrder_Red))
print(" ")
print("TemporalOrder_Clear")
print(summary(TemporalOrder_Clear))
print(" ")
print("DelayedAlternation")
print(summary(DelayedAlternation))
print(" ")
print("Cheeseboard_RawLatency")
print(summary(Cheeseboard_RawLatency))
print(" ")
print("Cheeseboard_ScaledLatency")
print(summary(Cheeseboard_ScaledLatency))
print(" ")
print("Cheeseboard_RawDistance")
print(summary(Cheeseboard_RawDistance))
print(" ")
print("Cheeseboard_ScaledDistance")
print(summary(Cheeseboard_ScaledDistance))
print(" ")
print("Capellini_Latency")
print(summary(Capellini_Latency))
print(" ")
print("Capellini_PawsTogether")
print(summary(Capellini_PawsTogether))
print(" ")
print("Capellini_NoContact")
print(summary(Capellini_NoContact))
print(" ")
print("Capellini_MouthPull")
print(summary(Capellini_MouthPull))
print(" ")
print("Capellini_OverallAtypical")
print(summary(Capellini_OverallAtypical))
print(" ")
print("Nesting_Contact")
print(summary(Nesting_Contact))
print(" ")
print("Nesting_Dig")
print(summary(Nesting_Dig))
print(" ")
print("Nesting_Complete")
print(summary(Nesting_Complete))
print(" ")
print("Neophagia_NovelFood")
print(summary(Neophagia_NovelFood))
print(" ")
print("Neophagia_NovelEnvironment")
print(summary(Neophagia_NovelEnvironment))
print(" ")
print("Neophagia_NovelBoth")
print(summary(Neophagia_NovelBoth))
print(" ")
print("Ladder_Raw")
print(summary(Ladder_Raw))
print(" ")
print("Ladder_Adjusted")
print(summary(Ladder_Adjusted))
print(" ")
print("Response_Learning")
print(summary(Response_Learning))
print(" ")
print("Reversal_Changepoint")
print(summary(Reversal_Changepoint))
print(" ")
print("Reversal_Perseverative")
print(summary(Reversal_Perseverative))
print(" ")
print("Reversal_Regressive")
print(summary(Reversal_Regressive))
sink()