data<-read.csv("~/Desktop/GITHUB_REPOS/Ts65DnPilots/Cheeseboard.csv", sep=",", head=TRUE)
data$GROUPS<-factor(data$GROUPS,c("2N", "Ts65Dn"))
data$DAYS<-as.factor(data$DAYS)
lineplot.CI(data$DAYS,data$LATENCY,group=data$GROUPS,type="b", x.cont=FALSE,col=c("Pink","Lightblue"), fixed=TRUE,lwd=3,cex.axis=1.25,ylab="Mean Latency (s)",xlab="Blocks of 4 Trials",cex.lab=1.5,cex.main=1.75,cex.leg=1.5, main="Dryland Version of the Morris Water Maze",pch="O",lty=c(1,6),x.leg=3.25)
quartz()
lineplot.CI(data$DAYS,data$PercentLATENCY,group=data$GROUPS,type="b", x.cont=FALSE,col=c("Pink","Lightblue"), fixed=TRUE,lwd=3,cex.axis=1.25,ylab="Percent Latency Compared to Block 1",xlab="Blocks of 4 Trials",cex.lab=1.5,cex.main=1.75,cex.leg=1.5, main="Dryland Version of the Morris Water Maze",pch="O",lty=c(1,6),x.leg=3.25)
quartz()
lineplot.CI(data$DAYS,data$DISTANCE,group=data$GROUPS,type="b", x.cont=FALSE,col=c("Pink","Lightblue"), fixed=TRUE,lwd=3,cex.axis=1.25,ylab="Mean Distance (cm)",xlab="Blocks of 4 Trials",cex.lab=1.5,cex.main=1.75,cex.leg=1.5, main="Dryland Version of the Morris Water Maze",pch="O",lty=c(1,6),x.leg=3.25)
quartz()
lineplot.CI(data$DAYS,data$PercentDISTANCE,group=data$GROUPS,type="b", x.cont=FALSE,col=c("Pink","Lightblue"), fixed=TRUE,lwd=3,cex.axis=1.25,ylab="Percent Distance Compared to Block 1",xlab="Blocks of 4 Trials",cex.lab=1.5,cex.main=1.75,cex.leg=1.5, main="Dryland Version of the Morris Water Maze",pch="O",lty=c(1,6),x.leg=3.25)
quartz()

lineplot.CI(response_learning$DAY, response_learning$Percent_Correct, group=response_learning$GROUP, x.leg=1,y.leg=90,col=c("Pink","Lightblue"), cex=1.25,lwd=3,ylab="Mean Percent Correct of 20 Trials", xlab="Day",main="Response Learning",cex.lab=1.25, cex.axis=1.25, cex.main=1.75,cex.leg=1.5)
quartz()
capellini<-read.csv("~/Desktop/GITHUB_REPOS/Ts65DnPilots/Capellini.csv", head=TRUE, sep=",")
par(mfrow=c(1,5))
par(oma=c(4,4,4,4))
par(lwd=2,cex.axis=1.25,cex.lab=1.25,cex.main=1.75)
capellini$GROUP<-factor(capellini$GROUP, c("2N","Ts65Dn"))
boxplot(capellini$Latency~capellini$GROUP, ylab="Latency to Consume Pasta",xlab="Group", col=c("Pink","Lightblue"))
boxplot(capellini$Atypical_Paw_Together~capellini$GROUP, ylab="Number of Times Paws Overlapped",xlab="Group", col=c("Pink","Lightblue"))
boxplot(capellini$Atypical_NoContact~capellini$GROUP, ylab="Number of Times the Paw Lost Contact",xlab="Group", col=c("Pink","Lightblue"))
boxplot(capellini$Atypical_Mouth_Pull~capellini$GROUP, ylab="Number of Mouth Pull Events",xlab="Group", col=c("Pink","Lightblue"))
boxplot(capellini$Sum_Atypical~capellini$GROUP, ylab="Total of Atypical Behaviors",xlab="Group", col=c("Pink","Lightblue"))
mtext("Capellini handling Test",side=3,outer=T,cex=1.2,line=2)
quartz()

par(mfrow=c(2,5))
par(oma=c(4,4,4,4))
par(lwd=2,cex.axis=1.25,cex.lab=1.25,cex.main=1.5)
plot(TEST$X2N,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="2N Subject 1",col="Pink")
plot(TEST$X2N.1,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="2N Subject 2",col="Pink")
plot(TEST$X2N.1,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="2N Subject 3",col="Pink")
plot(TEST$X2N.1,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="2N Subject 4",col="Pink")
plot(TEST$X2N.1,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="2N Subject 5",col="Pink")
plot(TEST$Ts65Dn,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="Ts65Dn Subject 1",col="lightblue")
plot(TEST$Ts65Dn.1,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="Ts65Dn Subject 2",col="lightblue")
plot(TEST$Ts65Dn.2,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="Ts65Dn Subject 3",col="lightblue")
plot(TEST$Ts65Dn.3,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="Ts65Dn Subject 4",col="lightblue")
plot(TEST$Ts65Dn.4,type="o",ylab="Choice (1=Reverse, 0= Perseverate)", xlab="Trial #",main="Ts65Dn Subject 5",col="lightblue")
mtext("Reversal Learning Test Performance",side=3,outer=T,cex=1.75,line=2)

par(mfrow=c(1,3))
par(oma=c(4,4,4,4))
boxplot(response_changeponts~group, ylab="Cumulative Behavioral Change Point",xlab="Group", main="Behavioral Change Point", col=c("Pink","Lightblue"),par(lwd=2,cex.axis=1.25,cex.lab=1.25,cex.main=1.75))
boxplot(response_perseverative~group, ylab="Perseverative Errors in 1st 20 Trials",xlab="Group", main="Perseverative Errors", col=c("Pink","Lightblue"),par(lwd=2,cex.axis=1.25,cex.lab=1.25,cex.main=1.75))
boxplot(response_regressive~group, ylab="Regressive Errors",xlab="Group", main="Regressive Errors", col=c("Pink","Lightblue"),par(lwd=2,cex.axis=1.25,cex.lab=1.25,cex.main=1.75))
mtext("Reversal Learning Test Performance",side=3,outer=T,cex=1.75,line=2)
